<a href="https://colab.research.google.com/github/dandihara/recommandation_practice/blob/main/%EC%BB%A8%ED%85%90%EC%B8%A0_%EA%B8%B0%EB%B0%98_%ED%95%84%ED%84%B0%EB%A7%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 신발간의 유사도를 이용 할 것이다.
# 가격 / 브랜드 / 착화감 / 경량성 / 편의성 순으로 데이터화
# 예시 데이터 제작
brand_list = ['Adidas','Nike','Jordan','New Balace']
product_list = []

import random

for i in range(10):
  tmp = {}
  tmp['price'] = random.randrange(90,200)*1000 # 9만부터 20만까지
  tmp['brand'] = brand_list[random.randrange(3)]
  tmp['grip_score'] = round(random.uniform(0,5),1)
  tmp['light_score'] = round(random.uniform(0,5),1)
  tmp['comfortable'] = round(random.uniform(0,5),1)

  product_list.append(tmp)

print(product_list)

[{'price': 92000, 'brand': 'Adidas', 'grip_score': 2.4, 'light_score': 1.7, 'comfortable': 1.1}, {'price': 109000, 'brand': 'Nike', 'grip_score': 0.9, 'light_score': 0.3, 'comfortable': 4.8}, {'price': 148000, 'brand': 'Nike', 'grip_score': 3.0, 'light_score': 4.6, 'comfortable': 3.9}, {'price': 145000, 'brand': 'Nike', 'grip_score': 4.8, 'light_score': 0.4, 'comfortable': 0.9}, {'price': 195000, 'brand': 'Jordan', 'grip_score': 3.5, 'light_score': 3.8, 'comfortable': 1.3}, {'price': 186000, 'brand': 'Jordan', 'grip_score': 3.4, 'light_score': 4.4, 'comfortable': 2.3}, {'price': 191000, 'brand': 'Adidas', 'grip_score': 2.5, 'light_score': 3.8, 'comfortable': 4.2}, {'price': 142000, 'brand': 'Adidas', 'grip_score': 4.6, 'light_score': 3.7, 'comfortable': 2.3}, {'price': 171000, 'brand': 'Adidas', 'grip_score': 0.3, 'light_score': 0.9, 'comfortable': 4.2}, {'price': 135000, 'brand': 'Jordan', 'grip_score': 1.0, 'light_score': 3.8, 'comfortable': 1.3}]


In [9]:
#코사인 유사도
#벡터의 내적을 이용하여 만든 계산
#벡터(데이터)가 이루는 각도의 값을 이용하여 계산
# 전혀 같은 곳이 안보임 = > -1 똑같다 1 그 사이 -1~1 사이

# (An * Bn)의 시그마값 / An제곱의 시그마 * Bn제곱의 시그마

import numpy as np
from numpy import dot #
from numpy.linalg import norm

def cos_sim(A,B):
  A = np.array(list(A.values())[2:])
  B = np.array(list(B.values())[2:])
  print(A,B)
  return dot(A,B) / (norm(A) * norm(B))

for i in range(len(product_list)):
  for j in range(len(product_list)):
    print(round(cos_sim(product_list[i],product_list[j]),4))

[2.4 1.7 1.1] [2.4 1.7 1.1]
1.0
[2.4 1.7 1.1] [0.9 0.3 4.8]
0.5174
[2.4 1.7 1.1] [3.  4.6 3.9]
0.913
[2.4 1.7 1.1] [4.8 0.4 0.9]
0.8573
[2.4 1.7 1.1] [3.5 3.8 1.3]
0.9738
[2.4 1.7 1.1] [3.4 4.4 2.3]
0.9616
[2.4 1.7 1.1] [2.5 3.8 4.2]
0.8786
[2.4 1.7 1.1] [4.6 3.7 2.3]
0.9983
[2.4 1.7 1.1] [0.3 0.9 4.2]
0.5081
[2.4 1.7 1.1] [1.  3.8 1.3]
0.7918
[0.9 0.3 4.8] [2.4 1.7 1.1]
0.5174
[0.9 0.3 4.8] [0.9 0.3 4.8]
1.0
[0.9 0.3 4.8] [3.  4.6 3.9]
0.6918
[0.9 0.3 4.8] [4.8 0.4 0.9]
0.3654
[0.9 0.3 4.8] [3.5 3.8 1.3]
0.404
[0.9 0.3 4.8] [3.4 4.4 2.3]
0.5237
[0.9 0.3 4.8] [2.5 3.8 4.2]
0.7774
[0.9 0.3 4.8] [4.6 3.7 2.3]
0.5255
[0.9 0.3 4.8] [0.3 0.9 4.2]
0.9825
[0.9 0.3 4.8] [1.  3.8 1.3]
0.4089
[3.  4.6 3.9] [2.4 1.7 1.1]
0.913
[3.  4.6 3.9] [0.9 0.3 4.8]
0.6918
[3.  4.6 3.9] [3.  4.6 3.9]
1.0
[3.  4.6 3.9] [4.8 0.4 0.9]
0.5984
[3.  4.6 3.9] [3.5 3.8 1.3]
0.921
[3.  4.6 3.9] [3.4 4.4 2.3]
0.9723
[3.  4.6 3.9] [2.5 3.8 4.2]
0.9918
[3.  4.6 3.9] [4.6 3.7 2.3]
0.9324
[3.  4.6 3.9] [0.3 0.9 4.2]
0.738

In [ ]:
# 유클리디안 유사도
# 유클리드 거리 - 두 점 사이의 거리를 계산하는 방식을 이용
# 두 점 사이의 거리 즉, 유클리드 거릿값이 클수록 유사도가 적은 것이고 작을수록 유사도가 높다. 작은 값부터 차례대로 유저에게 추천을 한다면 이론상은 맞다.
# 브랜드는 비교시에 같으면 1 아니면 0 으로

import math 

for i in range(len(product_list)):
  for j in range(len(product_list)):
    brand_flag  = 0
    if product_list[i]['brand'] == product_list[j]['brand']:
      brand_flag = 1
    dis = math.sqrt(pow(product_list[i]['grip_score']-product_list[j]['grip_score'],2) + pow(product_list[i]['light_score'] - product_list[j]['light_score'],2) + pow(product_list[i]['comfortable'] - product_list[j]['comfortable'],2))

In [ ]:
print(product_list[0])
print(product_list[9])

{'price': 114000, 'brand': 'Jordan', 'grip_score': 0.0, 'light_score': 1.7, 'comfortable': 1.8}
{'price': 96000, 'brand': 'Adidas', 'grip_score': 0.1, 'light_score': 1.3, 'comfortable': 1.1}
